# -*- coding: utf-8 -*-
"""CS06

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ziJRDbI4t0AA3QhgZ8EAqd1sAC6MvxRi
"""

!sudo apt update
!sudo apt install libcairo2-dev ffmpeg \
    texlive texlive-latex-extra texlive-fonts-extra \
    texlive-latex-recommended texlive-science \
    tipa libpango1.0-dev
!pip install manim
!pip install IPython --upgrade

from manim import *

# Commented out IPython magic to ensure Python compatibility.
# %%manim -pqh -v WARNING CK06
# 
# class CK06(Scene):
#   def construct(self):
#         titleText = Text("""
#             Mustang Math Tournament 2022: 
#             Pressure Round Round 1 #2
#         """)
#         self.play(Write(titleText))
#         self.wait(2)
#         self.play(FadeOut(titleText))
# 
#         tex = Tex(r"\text{Define the confused factorial of} n \text{(denoted } n?!\text{) as} \\ \text{the arithmetic mean of} (n-1)! \text{and} (n+1)!, \text{where} \\ n! = n $\cdot$ (n-1) $\cdots$ 3 $\cdot$ 2 $\cdot$ 1, \text{and }  0! = 1.  \text{If the sum }  \\ $\frac{1?!}{2!}$ + $\frac{2?!}{3!}$ + $\cdots$ + $\frac{20?!}{21!}$ \text{can be expressed as a reduced} \\ \text{common fraction} $\frac{a}{b}$. \text{compute the value of } a + b ", font_size=50)
#         self.play(Write(tex))
#         self.wait(30)
#         self.play(FadeOut(tex))
# 
#         first_line =  MathTex(r"\frac{1?!}{2!}+\frac{2?!}{3!}+\ldots+\frac{20?!}{21!}", font_size = 60)
#         second_line = MathTex(r"=\sum_{i=1}^{20} \frac{i?!}{(i+1)!}", font_size = 60)
#         third_line =  MathTex(r"= \sum_{i=1}^{20} \frac{(i-1)!+(i+1)!}{2(i+1)!}", font_size = 60)
#         fourth_line = MathTex(r"= \frac 12 \sum_{i=1}^{20} \frac{(i-1)!+(i+1)!}{(i+1)!}", font_size = 60)
#         fifth_line = MathTex(r"= \frac 12 \sum_{i=1}^{20} \left(\frac{(i-1)!}{(i+1)!}+1\right)", font_size = 60)
#         sixth_line = MathTex(r"= 10+\frac 12 \sum_{i=1}^{20} \frac{(i-1)!}{(i+1)!}", font_size = 60)
#         seventh_line = MathTex(r"= 10+\frac 12 \sum_{i=1}^{20} \frac{1}{i(i+1)}", font_size = 100)
# 
#         # Position second line underneath first line
#         second_line.next_to(first_line, DOWN)
#         fourth_line.next_to(third_line, DOWN)
#         sixth_line.next_to(fifth_line, DOWN)
#     
#         # Displaying text
#         self.wait(1)
#         self.play(Write(first_line))
#         self.play(first_line.animate.shift(UP))
#         self.wait(10)
#         self.play(Write(second_line))
#         self.wait(8)
#         self.play(ReplacementTransform(first_line, third_line), FadeOut(second_line))
#         self.play(third_line.animate.shift(UP))
#         self.wait(13)
#         self.play(Write(fourth_line))
#         self.wait(7)
#         self.play(ReplacementTransform(third_line, fifth_line), FadeOut(fourth_line))
#         self.wait(9)
#         self.play(fifth_line.animate.shift(UP))
#         self.play(Write(sixth_line))
#         self.wait(9)
#         self.play(ReplacementTransform(fifth_line, seventh_line), FadeOut(sixth_line))
#         self.wait(9)
#         self.play(FadeOut(seventh_line))
# 
#         #I-L
#         partial_frac_decomp = Tex(r"\boxed{\text{Partial Fraction Decomposition}}", font_size = 80)
#         self.play(Write(partial_frac_decomp))
#         self.wait(2)
#         self.play(FadeOut(partial_frac_decomp))
# 
#         line_J = MathTex(r"\frac{1}{i(i+1)} = \frac{A}{i}+\frac{B}{i+1}", font_size = 60)
#         line_K = MathTex(r"\implies 1=A(i+1)+Bi=(A+B)i+A", font_size = 60)
#         line_L = MathTex(r"\implies A+B=0, A=1 \implies A=1,B=-1 \implies \frac{1}{i(i+1)} = \frac 1i - \frac 1{i+1}", font_size = 45)
# 
#         line_K.next_to(line_J, DOWN)
#         line_L.next_to(line_K, DOWN)
# 
#         self.play(Write(line_J))
#         self.wait(9)
#         self.play(line_J.animate.shift(UP))
#         self.play(line_J.animate.shift(UP))
#         self.play(Write(line_K))
#         self.wait(9)
#         self.play(line_K.animate.shift(UP))
#         self.play(Write(line_L))
#         self.wait(13)
#         self.play(FadeOut(line_J))
#         self.play(FadeOut(line_K))
#         self.play(FadeOut(line_L))
# 
#         line_M = Tex(r"$10+\frac 12 \sum_{i=1}^{20} \frac{1}{i(i+1)}= 10+\frac 12 \sum_{i=1}^{20} \left(\frac 1i - \frac 1{i+1}\right)$", font_size = 70)
#         line_N = MathTex(r"= 10+\frac 12 \left(\frac 11 - \frac 1{21}\right) = \frac{220}{21}.", font_size = 80)
#         line_O = MathTex(r"\boxed{241}", font_size = 100)
# 
#         self.play(Write(line_M))
#         self.wait(16)
#         self.play(ReplacementTransform(line_M, line_N))
#         self.wait(9)
#         self.play(ReplacementTransform(line_N, line_O))
#         self.wait(5)
#         self.play(FadeOut(line_O))
# 
#         
# 
#         
#         #AT THE END, TRANSFORM INTO ONE LARGE BLOCK OF TEXT WITH ALL
# 
# 
# 
#         
#         # \text{If the sum }  \\ \frac{1?!}{2!} + \frac{2?!}{3!} + ... + \frac{20?!}{21!} \text{can be expressed as} \\\text{a reduced common fraction} \frac{a}{b}. \text{compute the value of } a + b
#         #\text{)as the arithmetic mean of} (n-1)! \tex{and} (n+1)!, \tex{where} \\ n! = n * (n-1) ... 3* 2* 1, \tex{and} 0! = 1. \tex{If the sum} \\ \frac{1?!}{2!} + \frac{2?!}{3!} + ... + \frac{20?!}{21!}
# 
#         
#     
# 
#

"""

*   wait 1 more second
*   List item

"""