# -*- coding: utf-8 -*-
"""YS07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IoXWgutH3rCDEDRecviUR-V7B9m23JHy
"""

!sudo apt update
!sudo apt install libcairo2-dev ffmpeg \
    texlive texlive-latex-extra texlive-fonts-extra \
    texlive-latex-recommended texlive-science \
    tipa libpango1.0-dev
!pip install manim
!pip install IPython --upgrade

from manim import *

# Commented out IPython magic to ensure Python compatibility.
# %%manim -pqh -v WARNING YS07
# 
# class YS07(Scene):
#   def construct(self):
#     title = Tex(r"Mustang Math 2022 \\ Pressure Round Round 2 Problem 1", font_size = 80)
#     self.play(Write(title))
#     self.wait(2)
#     self.play(FadeOut(title))
# 
#     problem = Tex(r"Alon selects two $($not necessarily distinct$)$ \text{factors} \\ of $20^{22}$.If the probability that at least one of these \\ factors is divisible by the other can be expressed as a \\ reduced common fraction $\frac{a}{b}$, compute the value of a+b.", font_size = 55)
#     self.play(Write(problem))
#     self.wait(14)
#     self.play(FadeOut(problem))
# 
#     first = Tex(r"$20^{22}$", font_size = 100)
#     prime_first = Tex(r"$2^{44} \cdot 5^{22}$", font_size = 100)
#     
#     self.play(Write(first))
#     self.wait(2)
#     self.play(ReplacementTransform(first, prime_first))
#     self.wait(2)
#     self.play(FadeOut(prime_first))
# 
#     a = Tex(r"a", font_size = 100)
#     b = Tex(r"b", font_size = 100)
#     c = Tex(r"-", font_size = 300)
# 
#     b.next_to(a, DOWN)
# 
#     a.shift(UP)
#     self.play(Write(a))
#     self.play(Write(b))
#     self.wait(1)
#     self.play(Write(c))
#     self.wait(2)
#     self.play(FadeOut(a))
#     self.play(FadeOut(b))
#     self.play(FadeOut(c))
# 
#     ex1 = Tex(r"$\frac{a}{b}$ = $\frac{2^{12} \cdot 5^9}{2^{12} \cdot 5^7}$", font_size = 120)
#     ex11 = Tex(r" = $5^2$ = 25", font_size = 100)
#     ex2 = Tex(r"$\frac{a}{b} = \frac{2^{12} \cdot 5^7}{2^{12} \cdot 5^9}$", font_size = 120)
#     ex22 = Tex(r"$ = \frac{1}{5^2} = \frac{1}{25}$", font_size = 100)
# 
#     self.play(Write(ex1))
#     self.wait(1)
#     self.play(ReplacementTransform(ex1, ex11))
#     self.wait(1)
#     self.play(FadeOut(ex11))
#     self.play(Write(ex2))
#     self.wait(1)
#     self.play(ReplacementTransform(ex2, ex22))
#     self.wait(1)
#     self.play(FadeOut(ex22))
#     
#     two = Tex(r"$2^{44}$", font_size = 120)
#     two_expand = Tex(r"0, 1, 2, $\cdots$ 43, 44", font_size = 120)
#     two_equals = Tex(r"$\frac{1}{45}$", font_size = 120)
# 
#     self.play(Write(two))
#     self.wait(1)
#     self.play(ReplacementTransform(two, two_expand))
#     self.wait(1)
#     self.play(ReplacementTransform(two_expand, two_equals))
#     self.wait(1)
#     self.play(FadeOut(two_equals))
#     two_equals.next_to(two_equals, RIGHT)
#     two_equals.next_to(two_equals, RIGHT)
#     two_equals.next_to(two_equals, RIGHT)
#     two_equals.next_to(two_equals, RIGHT)
#     two_equals.next_to(two_equals, RIGHT)
#     two_equals.next_to(two_equals, UP)
#     self.play(Write(two_equals))
#     self.wait(1)  
# 
#     x1 = Tex(r"$\frac{a}{b}$ = $\frac{2^x \cdot 5^y}{2^h \cdot 5^k}$", font_size = 120) 
#     x2 = Tex(r"$x < h$", font_size = 120)
#     x3 = Tex(r"$\frac{a}{b}$ = $\frac{2^{12} \cdot 5^9}{2^6 \cdot 5^7}$", font_size = 120)
#     x3 = Tex(r" = $2^6$ $\cdot$ $5^2$ = 1600", font_size = 100)
#     x4 = Tex(r"$\frac{a}{b} = \frac{2^{17} \cdot 5^3}{2^6 \cdot 5^{12}}$", font_size = 120)
#     x5 = Tex(r"$ = \frac{2^{11} }{5^9} = \frac{2048}{1953125}$", font_size = 100)
#     x6 = Tex(r"y $\le$ k", font_size = 120)
# 
#     self.play(Write(x1))
#     self.wait(2)
#     self.play(ReplacementTransform(x1, x2))
#     self.wait(1)
#     self.play(ReplacementTransform(x2, x3))
#     self.wait(1)
#     self.play(ReplacementTransform(x3, x4))
#     self.wait(1)
#     self.play(ReplacementTransform(x4, x5))
#     self.wait(1)
#     self.play(ReplacementTransform(x5, x6))
#     self.wait(2)
#     self.play(FadeOut(x6))
# 
#     y1 = Tex(r"$5^{22}$", font_size = 120)
#     y2 = Tex(r"0, 1, 2, $\cdots$, 21, 22", font_size = 100)
#     y3 = Tex(r"$\frac{1}{23}$", font_size = 120)
# 
#     self.play(Write(y1))
#     self.wait(1)
#     self.play(ReplacementTransform(y1, y2))
#     self.wait(1)
#     self.play(ReplacementTransform(y2, y3))
#     self.wait(1)
#     self.play(FadeOut(y3))
#     y3.next_to(y3, RIGHT)
#     y3.next_to(y3, RIGHT)
#     y3.next_to(y3, RIGHT)
#     y3.next_to(y3, RIGHT)
#     y3.next_to(y3, RIGHT)
#     self.play(Write(y3))
#     self.wait(1)
#     
#     z1 = Tex(r"=", font_size = 150)
#     z2 = Tex(r"$<$", font_size = 150)
#     z3 = Tex(r"$>$", font_size = 150)
#     z4 = Tex(r"$\frac{1}{2} \cdot (1 - \frac{1}{23}) + $", font_size = 120)
#     z5 = Tex(r"$\frac{12}{23}$", font_size = 120)
#     z6 = Tex(r"$\frac{12}{23} \cdot \frac{44}{45} + \frac{1}{45}$", font_size = 120)
#     z7 = Tex(r"$\frac{551}{1035}$", font_size = 120)
#     z8 = Tex(r"551 + 1035 = \boxed{1586}", font_size = 120)
# 
#     self.play(Write(z1))
#     self.wait(1)
#     self.play(ReplacementTransform(z1, z2))
#     self.wait(1)
#     self.play(ReplacementTransform(z2, z3))
#     self.wait(1)
#     self.play(FadeOut(z3))
#     self.play(Write(z4))
#     self.play(y3.animate.shift(LEFT))
#     self.play(y3.animate.shift(LEFT))
#     self.play(ReplacementTransform(z4, z5), FadeOut(y3))
#     self.play(ReplacementTransform(z5, z6), FadeOut(two_equals))
#     self.wait(1)
#     self.play(ReplacementTransform(z6, z7))
#     self.wait(1)
#     self.play(ReplacementTransform(z7, z8))
#     self.wait(2)
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
#   
# 
# 
# 
# 
#

"""Alon selects two (not necessarily distinct) factors of 20^22. If the probability that at least one of these factors is divisible by the other can be expressed as a reduced common fraction a/b, compute the value of a+b. (bring in center, raise to top)"""

ex1 = Tex(r"$\frac{a}{b} = \frac{2^12 \cdot 5^9}{2^12 \cdot 5^7}$", font_size = 80)
    ex11 = Tex(r" = 5^2 = 25", font_size = 80)
    ex2 = Tex(r"$\frac{a}{b} = \frac{2^12 \cdot 5^7}{2^12 \cdot 5^9}$", font_size = 80)
    ex22 = Tex(r"$ = \frac{1}{5^2} = \frac{1}{25}$", font_size = 80)

    self.play(Write(ex1))
    self.wait(1)
    self.play(ReplacementTransform(ex1, ex11))
    self.wait(1)
    self.play(FadeOut(ex11))
    self.play(Write(ex2))
    self.wait(1)
    self.play(ReplacementTransform(ex2, ex22))
    self.wait(1)
    self.play(FadeOut(ex22))